spring:
  datasource:
    url: jdbc:mysql://192.168.31.207:3306/passbook
    password: root
    username: root
  kafka:
    consumer:
      group-id: test-consumer-group
      enable-auto-commit: true
      auto-offset-reset: earliest
      bootstrap-servers: 192.168.31.207:9092
  redis:
    host: 192.168.31.207
    port: 6379
server:
  port: 9528
logging:
  level:
    root: INFO
  path: log